#!/bin/bash
# Houdini Agent - Enhanced Commands
# ✨ Now with 10-100x faster native accessibility!

# ============================================
# FEATURES (as of Jan 2026)
# ============================================
# ✅ Native macOS Accessibility API (10-100x faster)
# ✅ Human-like cursor movements (undetectable)
# ✅ Instant text entry via AXValue
# ✅ Smart fallbacks when native methods fail
# ✅ Continuous loop mode with state awareness
# ✅ Pattern learning from repeated tasks
# ============================================

# ============================================
# ACTIVATION (Run this first!)
# ============================================
source .venv/bin/activate

# Or use this one-liner:
# cd /Users/letsfuck/Desktop/Houdini/houdini-agent && source .venv/bin/activate

# ============================================
# BASIC USAGE (Enhanced Mode ON by default!)
# ============================================

# Enhanced mode is NOW THE DEFAULT - 10-100x faster! ⚡
python -m src.main --task "open calculator"

# Explicitly enable enhanced (though it's default)
python -m src.main --task "open whatsapp" --use-enhanced

# Disable enhanced if you want old behavior
python -m src.main --task "open Safari" --no-enhanced

# ============================================
# PERFORMANCE COMPARISON
# ============================================

# OLD (--no-enhanced): ~2-3 seconds per element find
# python -m src.main --task "click submit button" --no-enhanced

 # NEW (default): ~0.002 seconds per element find! 🚀
# python -m src.main --task "click submit button"

# ============================================
# LOOP MODE (Continuous State Awareness)
# ============================================

# Loop mode with enhanced executor (RECOMMENDED!)
python -m src.main --task "open Safari and search for weather" --loop

# Loop mode without supervisor (faster, less monitoring)
python -m src.main --task "open calculator" --loop --no-supervisor

# Loop mode with checkpoint-based supervision
python -m src.main --task "open Chrome and search Google" --loop --supervisor-mode checkpoint

# AI-powered verification - checks if task is complete
python -m src.main --task "create a folder named test on desktop" --loop

# ============================================
# APPLICATION TASKS
# ============================================

# These now use native accessibility for instant app opening
python -m src.main --task "open Safari"
python -m src.main --task "open Finder"
python -m src.main --task "open Notes"
python -m src.main --task "open Terminal"
python -m src.main --task "open System Settings"

# ============================================
# BROWSER TASKS (Super Fast Now!)
# ============================================

# Element finding is now 2100x faster!
python -m src.main --task "open Chrome and go to google.com" --loop
python -m src.main --task "open Safari and search for weather" --loop
python -m src.main --task "open Firefox and go to youtube.com" --loop

# Complex multi-step with enhanced understanding
python -m src.main --task "open Chrome, go to gmail.com, and compose a new email" --loop

# ============================================
# FILE OPERATIONS
# ============================================

python -m src.main --task "open Finder and create a new folder on desktop"
python -m src.main --task "open Downloads folder"
python -m src.main --task "create a text file named notes.txt on desktop" --loop

# ============================================
# PRODUCTIVITY TASKS
# ============================================

python -m src.main --task "open Notes and create a new note"
python -m src.main --task "open Calendar"
python -m src.main --task "open Messages"

# ============================================
# ADVANCED: ELEMENT-BASED ACTIONS
# ============================================

# The enhanced executor can find elements by text automatically!
# OLD way: Find coordinates manually
# NEW way: Just describe the element

# Example: "click:Submit" finds button with "Submit" text
# Example: "type:Email:user@example.com" finds Email field and types

# These actions are generated by the planner automatically

# ============================================
# PATTERN LEARNING - View learned patterns
# ============================================

# View pattern statistics  
python -c "from src.utils.pattern_store import pattern_store; import json; print(json.dumps(pattern_store.get_statistics(), indent=2))"

# View choice tracker statistics
python -c "from src.utils.choice_tracker import choice_tracker; import json; print(json.dumps(choice_tracker.get_statistics(), indent=2))"

# View high confidence patterns (>80%)
python -c "from src.utils.pattern_store import pattern_store; ps = pattern_store.get_high_confidence_patterns(0.8); print(f'{len(ps)} high confidence patterns')"

# ============================================
# TESTING NEW FEATURES
# ============================================

# Run test suite to verify everything works
python test_new_features.py

# Test human-like cursor (will move cursor naturally)
python -c "from src.utils.cursor_controller import HumanCursor; import pyautogui; c = HumanCursor(); x, y = pyautogui.position(); c.move_to(x+100, y+100); print('Cursor moved with human-like bezier curve!')"

# Test native accessibility speed
python -c "from src.utils.accessibility_api import AccessibilityAPI; import time; api = AccessibilityAPI(); start = time.time(); tree = api.get_ui_tree(); print(f'Found UI tree in {time.time()-start:.3f}s')"

# ============================================
# DEBUGGING OPTIONS
# ============================================

# Limit steps for testing
python -m src.main --task "open calculator" --steps 3

# Disable enhanced executor for troubleshooting
python -m src.main --task "open Safari" --no-enhanced

# View help
python -m src.main --help

# ============================================
# PERFORMANCE STATS
# ============================================

# After running tasks with enhanced mode, you'll see stats like:
# 📊 Stats: 5 native, 2 cursor, 1 fallback
# ⚡ Speed: 0.012s per action, 63% native

# This means:
# - 5 actions used native accessibility (instant!)
# - 2 actions used human-like cursor
# - 1 action used fallback (keyboard shortcut)
# - Average 0.012s per action (vs 2-3s with old method)
# - 63% of actions were native (very fast!)

# ============================================
# TROUBLESHOOTING
# ============================================

# If you see "Enhanced executor not available":
# pip install pyobjc-core pyobjc-framework-Cocoa pyobjc-framework-Quartz

# If you need accessibility permissions:
# System Settings → Privacy & Security → Accessibility
# Add Terminal/Your IDE to allowed apps

# If enhanced mode fails:
# Use --no-enhanced flag to fallback to basic mode
# python -m src.main --task "your task" --no-enhanced
