"""
LangGraph State Schema for Houdini Agent.

This module defines the TypedDict state that flows through the LangGraph
execution graph. It combines and modernizes the state from:
- LoopState (legacy coordinator)
- AdaptiveState (adaptive coordinator)

Benefits of LangGraph:
- Built-in checkpointing for crash recovery
- State persistence across sessions
- Human-in-the-loop hooks
- Clear node-based execution flow
- Automatic state management
"""

from typing import TypedDict, Optional, List, Dict, Any, Annotated
from datetime import datetime
from enum import Enum
import operator


class AgentPhase(str, Enum):
    """Current phase of agent execution."""
    INITIALIZING = "initializing"
    PLANNING = "planning"
    EXECUTING = "executing"
    SUPERVISOR_GUIDE = "supervisor_guide"
    VERIFYING = "verifying"
    EVOLVING = "evolving"
    HUMAN_INPUT = "human_input"  # For human-in-the-loop
    COMPLETED = "completed"
    FAILED = "failed"


class MacroStep(TypedDict):
    """A high-level step from the planner."""
    step: str
    context: str
    potential_issues: Optional[str]


class MicroAction(TypedDict):
    """A low-level action from the executor."""
    type: str  # "hotkey", "type", "click", "wait", "key"
    params: Dict[str, Any]
    description: str
    requires_screen: Optional[bool]


class ScreenContext(TypedDict):
    """Current screen state information."""
    app_name: str
    window_title: str
    visible_elements: List[Dict[str, Any]]
    screenshot_path: Optional[str]
    timestamp: str


class ActionRecord(TypedDict):
    """Record of an executed action."""
    type: str
    params: Dict[str, Any]
    description: str
    timestamp: str
    success: bool
    error: Optional[str]


class SupervisorIntervention(TypedDict):
    """Record of a supervisor intervention."""
    timestamp: str
    reason: str
    decision: str
    correction: Optional[str]


# Reducer functions for list state updates
def add_to_list(existing: List, new: List) -> List:
    """Append new items to existing list."""
    return existing + new


def replace_value(existing: Any, new: Any) -> Any:
    """Replace existing value with new value."""
    return new


class HoudiniAgentState(TypedDict):
    """
    Main state schema for LangGraph-based Houdini Agent.
    
    This state flows through all nodes in the graph:
    - planner_node: Generates macro plan
    - executor_node: Generates and executes micro actions
    - supervisor_node: Monitors and guides
    - verifier_node: Verifies completion
    - human_node: Handles human input (optional)
    
    Annotated fields with operator.add will accumulate values.
    """
    
    # ========== TASK INFO ==========
    task_id: str
    task: str
    phase: str  # AgentPhase value
    
    # ========== PLANNING STATE ==========
    macro_steps: List[MacroStep]
    expected_outcome: str
    success_criteria: str
    current_macro_step_idx: int
    
    # ========== EXECUTION STATE ==========
    # Actions to execute (generated by executor)
    pending_actions: List[MicroAction]
    
    # Executed actions history (accumulates)
    executed_actions: Annotated[List[ActionRecord], operator.add]
    
    # Current execution result
    last_action_success: bool
    last_action_error: Optional[str]
    
    # ========== SCREEN CONTEXT ==========
    current_screen: Optional[ScreenContext]
    screen_history: Annotated[List[ScreenContext], operator.add]
    
    # ========== SUPERVISOR STATE ==========
    needs_supervisor: bool
    supervisor_reason: Optional[str]
    interventions: Annotated[List[SupervisorIntervention], operator.add]
    supervisor_notes: Annotated[List[str], operator.add]
    
    # ========== VERIFICATION STATE ==========
    verification_complete: bool
    verification_confidence: float
    verification_reason: Optional[str]
    corrective_steps: List[MacroStep]
    
    # ========== EVOLUTION STATE ==========
    evolution_count: int
    max_evolutions: int
    
    # ========== PROBABILITY/FLEXIBILITY (from probability model) ==========
    task_flexibility: Optional[Dict[str, Any]]
    uncertainty_score: float
    execution_params: Optional[Dict[str, Any]]
    
    # ========== TIMESTAMPS ==========
    started_at: Optional[str]
    completed_at: Optional[str]
    
    # ========== ITERATION CONTROL ==========
    iteration: int
    max_iterations: int
    
    # ========== HUMAN-IN-THE-LOOP ==========
    awaiting_human_input: bool
    human_input_prompt: Optional[str]
    human_input_response: Optional[str]
    
    # ========== ERROR HANDLING ==========
    error: Optional[str]
    should_abort: bool


def create_initial_state(
    task: str,
    task_id: Optional[str] = None,
    max_iterations: int = 100,
    max_evolutions: int = 3
) -> HoudiniAgentState:
    """
    Create the initial state for a new task execution.
    
    Args:
        task: Natural language task description
        task_id: Optional unique identifier (generated if not provided)
        max_iterations: Maximum execution iterations
        max_evolutions: Maximum task evolutions before abort
    
    Returns:
        Initial HoudiniAgentState
    """
    import uuid
    
    return HoudiniAgentState(
        # Task info
        task_id=task_id or str(uuid.uuid4())[:8],
        task=task,
        phase=AgentPhase.INITIALIZING.value,
        
        # Planning
        macro_steps=[],
        expected_outcome="",
        success_criteria="",
        current_macro_step_idx=0,
        
        # Execution
        pending_actions=[],
        executed_actions=[],
        last_action_success=True,
        last_action_error=None,
        
        # Screen
        current_screen=None,
        screen_history=[],
        
        # Supervisor
        needs_supervisor=False,
        supervisor_reason=None,
        interventions=[],
        supervisor_notes=[],
        
        # Verification
        verification_complete=False,
        verification_confidence=0.0,
        verification_reason=None,
        corrective_steps=[],
        
        # Evolution
        evolution_count=0,
        max_evolutions=max_evolutions,
        
        # Probability model
        task_flexibility=None,
        uncertainty_score=0.0,
        execution_params=None,
        
        # Timestamps
        started_at=datetime.now().isoformat(),
        completed_at=None,
        
        # Iteration control
        iteration=0,
        max_iterations=max_iterations,
        
        # Human-in-the-loop
        awaiting_human_input=False,
        human_input_prompt=None,
        human_input_response=None,
        
        # Error handling
        error=None,
        should_abort=False,
    )


def state_to_context_prompt(state: HoudiniAgentState) -> str:
    """
    Generate a context prompt from current state.
    This can be passed to LLM calls to maintain awareness.
    """
    executed_count = len(state.get("executed_actions", []))
    macro_count = len(state.get("macro_steps", []))
    current_idx = state.get("current_macro_step_idx", 0)
    
    current_step = ""
    if macro_count > 0 and current_idx < macro_count:
        current_step = state["macro_steps"][current_idx].get("step", "Unknown")
    
    screen = state.get("current_screen")
    screen_info = "Not captured"
    if screen:
        screen_info = f"{screen.get('app_name', 'Unknown')} - {screen.get('window_title', '')}"
    
    return f"""=== CURRENT STATE ===
Task: {state.get('task', 'Unknown')}
Phase: {state.get('phase', 'Unknown')}
Progress: Step {current_idx + 1}/{macro_count}
Current Step: {current_step}
Actions Executed: {executed_count}
Screen: {screen_info}
Interventions: {len(state.get('interventions', []))}
Evolution: {state.get('evolution_count', 0)}/{state.get('max_evolutions', 3)}
Iteration: {state.get('iteration', 0)}/{state.get('max_iterations', 100)}
======================"""
